# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Much faster string slugifier
#'
#' @param x string to slugify
#' @param repl what to replace whitespace with; defaults to `'`
#' @param lower turn slugified string into lowercase? defaults to `TRUE`
#' @return string
#' @export
#' @examples
#' slugify_basic("R is great!")
slugify_fast <- function(x, repl = "-", lower = TRUE) {
    .Call(`_slugify_slugify_fast`, x, repl, lower)
}

